### ISSUE TITLE
Dimension API is returning up to 3 Elements in Support Value list

### ISSUE THREAD

**Issue by camjones1708** [pitchmuc/adobe-analytics-api-2.0#101]
When leveraging 'full' on getDimensions, it is failing due to `df_dims.support.values.tolist()` returning up to 3 elements where only 2 column names are specified. Changing below should resolve the issue.
columns=['support_oberon', 'support_dw']
to
columns=['support_oberon', 'support_dw','support_realtime']

**Comment by pitchmuc** [comment]
Thanks @camjones1708 
Yes, apparently, the API response has changed at the beginning of the year. 
@loldenburg has already suggested a fix, hopefully live tomorrow.

**Comment by camjones1708** [comment]
I can confirm that fix solved my problem. One additional note is that the `standardComponent` column has a mixed dataType. I don't need it so I am dropping it. But that is a problem when converting to a spark Dataframe. Thanks for the quick follow up.

**Comment by pitchmuc** [comment]
you mean your fix @camjones1708 ?

**Comment by pitchmuc** [comment]
New verison is live with your fix ;) 

Thanks again
