### ISSUE TITLE
getClassificationDataset does not work

### ISSUE THREAD

**Issue by loldenburg** [pitchmuc/adobe-analytics-api-2.0#109]
![image](https://github.com/pitchmuc/adobe-analytics-api-2.0/assets/16238928/867084eb-ff65-4ef2-a129-925a436e3127)

causes AttributeError: 'Analytics' object has no attribute '_endpoint_classification'

**Comment by pitchmuc** [comment]
Working on it and adding the methods they added later and also fixed. 
It is not easy, you can definitely pay me a beer if you integrate that in your solution 
The documentation is somehow even worse than normal adobe standard....

**Comment by loldenburg** [comment]
That does not surprise me given the quality of Classification Sets in
general. I am not planning to integrate Classification management, I just
saw this issue by accident when trying sth else...
I will buy you a beer anyway... :D

**Comment by pitchmuc** [comment]
New version is live today : `0.4.2.post1`
