### ISSUE TITLE
Algorithm 'RS256' could not be found in python

### ISSUE THREAD

**Issue by akashachanta01** [pitchmuc/adobe-analytics-api-2.0#54]
Hi , 

When I tried to run cids = api2.retrieveToken() after importing the configfile I get an error telling "Algorithm 'RS256' could not be found. Do you have cryptography installed? " I have the cryptography package installed and pyJWT package installed as well. I'm not sure what issue is here ?

**Comment by pitchmuc** [comment]
Hello
Try to install that library: 
PyJWT[crypto]>=1.7.1 

Also retrieveToken is not really supported anymore.

I would recommend to use `Login` class and go to the class retrieve the token from there. 

```python
login = api2.Login()
login.connector.token ## getting the token
or 
login.header ## will provide you the required information

```

**Comment by akashachanta01** [comment]
I tried it but no luck and I still get same error

**Comment by pitchmuc** [comment]
Several options I can provide:
* You can try to upgrade pyJWT to 2.0.0 
* you can uninstall pyjwt and jwt and re-install one after the other 

Are you using your local environment or are you on Google Cloud ? We have seen this issue coming from Google Collab, and it is a Google issue.

**Comment by akashachanta01** [comment]
I was able to fix the issue I think but now I get a different error , I ran this cids = api2.getCompanyId() and I get this error 

![image](https://user-images.githubusercontent.com/39563268/116907409-802f4300-ac0f-11eb-9418-9bcb56674214.png)

**Comment by pitchmuc** [comment]
I would recommend to use the `Login` class as explained in my first answer.
The `api2.getCompanyId()` is not supported anymore. 

What was the issue / or the resolution on the first isse ? It would be interesting for others.

**Comment by akashachanta01** [comment]
I did pip uninstall pyjwt first and then conda install pyjwt -y. for the above issue , I had to do conda upgrade cryptography . Now it is working fine .

**Comment by pitchmuc** [comment]
Awesome to know. 
Thanks for the feedback. Have fun !
