### ISSUE TITLE
Issue with findComponentsUsage function after last update

### ISSUE THREAD

**Issue by frederikwerner** [pitchmuc/adobe-analytics-api-2.0#56]
The last update introduced new functionality to the awesome findComponentsUsage function. Unfortunately, it now produces an error when called:
```
retrieving segments
retrieving calculated metrics
retrieving projects details - long process
Traceback (most recent call last):
  File "d:\Projects\AA_Logs\aapy.py", line 177, in <module>
    findings = mycompany.findComponentsUsage(myElements,verbose=True,recursive=True,rsidPrefix=True)
  File "C:\Python\lib\site-packages\aanalytics2\aanalytics2.py", line 1564, in findComponentsUsage
    self.projectDetails = self.getAllProjectDetails(verbose=verbose,rsidPrefix=rsidPrefix)
TypeError: getAllProjectDetails() got an unexpected keyword argument 'rsidPrefix'
```
From my investigations, I found that a parameter for the getAllProjectDetails function might have been renamed independently from the findComponentsUsage function. Specifically, if I change `self.projectDetails = self.getAllProjectDetails(verbose=verbose,rsidPrefix=rsidPrefix)` to `self.projectDetails = self.getAllProjectDetails(verbose=verbose,rsidSuffix=rsidPrefix)`, the function works again.

**Comment by pitchmuc** [comment]
Sorry, stupid mistake on that one, the parameter is rsidSuffix as you described, for unknown reason I call it rsidPredix. 
it will be fixed in the next patch release.

**Comment by pitchmuc** [comment]
It should be fixed in the last commit.
Could you test the last commit 2f76cb1 ?
`pip install git+https://github.com/pitchmuc/adobe-analytics-api-2.0.git@2f76cb129b3e0582988a9ce9ae6b22124f9cc76f`

**Comment by frederikwerner** [comment]
This issue seems to be fixed now :)
