### ISSUE TITLE
findComponentsUsage function fails

### ISSUE THREAD

**Issue by frederikwerner** [pitchmuc/adobe-analytics-api-2.0#57]
When I use the findComponentsUsage function, it fails with this log:
```
retrieving segments
retrieving calculated metrics
retrieving projects details - long process
1344 project details to retrieve
estimated time required : 22 minutes
search started
recursive option : True
start looking into segments
start looking into calculated metrics
start looking into projects
Traceback (most recent call last):
  File "d:\Projects\AA_Logs\aapy.py", line 177, in <module>
    findings = mycompany.findComponentsUsage(myElements,verbose=True,recursive=True,rsidPrefix=True)
  File "C:\Python\lib\site-packages\aanalytics2\aanalytics2.py", line 1669, in findComponentsUsage
    for element in proj['segments']:
KeyError: 'segments'
```
Happy to help debug this, but this is all the information I have right now.

**Comment by pitchmuc** [comment]
Thanks @frederikwerner, 
From the look of your statement that you passed (thank god, you used the verbose option :) ). I can see you are trying to get the recursive version where I also look inside the segment and calculated metrics that I found during the first phase. 

I tried to be smart and created a generator of your Project dictionary, it saved memory usage during the function runtime. 
However, when recursive option is used, it tries to go to the projects again, but the generator is already exhausted. 
I created a back up of the Projects details generator that will be used in case the recursive option is used.

**Comment by pitchmuc** [comment]
It should be fixed in the last commit.
Could you test the last commit 2f76cb1 ?
`pip install git+https://github.com/pitchmuc/adobe-analytics-api-2.0.git@2f76cb129b3e0582988a9ce9ae6b22124f9cc76f`

**Comment by frederikwerner** [comment]
I just tried it, but got a new error:
0.2.7-1
retrieving segments
retrieving calculated metrics
retrieving projects details - long process
1345 project details to retrieve
estimated time required : 22 minutes
search started
recursive option : True
start looking into segments
start looking into calculated metrics
start looking into projects
start looking into recursive elements
Traceback (most recent call last):
  File "d:\Projects\AA_Logs\aapy.py", line 178, in <module>
    findings = mycompany.findComponentsUsage(myElements,verbose=True,recursive=True,rsidSuffix=True)
  File "C:\Python\lib\site-packages\aanalytics2\aanalytics2.py", line 1679, in findComponentsUsage
    for element in proj.get('segments',[]):
AttributeError: 'itertools._tee' object has no attribute 'get'

**Comment by pitchmuc** [comment]
I found the issue, the duplication of the generator was more complex than I thought. 
Fix is uploaded with the 09c1fef commit

*FYI*: the recursive search is not "double recursive" (search dimension in the segment of a calculated metrics). 
I am considering adding this functionality in the future now that I have the scanCalculatedMetric method but I need to see how I can handle the response in the current format.

**Comment by frederikwerner** [comment]
Hm, still gives me an error:
0.2.7-1
retrieving segments
retrieving calculated metrics
retrieving projects details - long process
1345 project details to retrieve
estimated time required : 22 minutes
search started
recursive option : True
start looking into segments
start looking into calculated metrics
start looking into projects
start looking into recursive elements
Traceback (most recent call last):
  File "d:\Projects\AA_Logs\aapy.py", line 178, in <module>
    findings = mycompany.findComponentsUsage(myElements,verbose=True,recursive=True,rsidSuffix=True)
  File "C:\Python\lib\site-packages\aanalytics2\aanalytics2.py", line 1679, in findComponentsUsage
    for element in proj.get('segments',[]):
AttributeError: 'itertools._tee' object has no attribute 'get'

**Comment by pitchmuc** [comment]
what ? :( 
have you re-install the library with the latest commit ?  
`pip install git+https://github.com/pitchmuc/adobe-analytics-api-2.0.git@09c1fefd2ebba66ce781763046e6f8773d03d1e4`

**Comment by frederikwerner** [comment]
Yeah, didn't help :/

**Comment by pitchmuc** [comment]
Could you try to uninstall the aanalytics2 library and install it again with the git install ? 
`pip uninstall aanalytics2`

I am considering that because I didn't increase the version, you do not get the last fix. 

`pip install git+https://github.com/pitchmuc/adobe-analytics-api-2.0.git@09c1fefd2ebba66ce781763046e6f8773d03d1e4`

**Comment by frederikwerner** [comment]
That helped, the error is gone! Thanks a lot!
