### ISSUE TITLE
findComponentsUsage   KeyError: 'reportlet'

### ISSUE THREAD

**Issue by nedwards-loop** [pitchmuc/adobe-analytics-api-2.0#63]
`myElements = ['555fa11fe4b0e34068484fc5']
findings= mycompany1.findComponentsUsage(myElements, verbose = True)`

retrieving segments
retrieving calculated metrics
retrieving projects details - long process
3953 project details to retrieve
estimated time required : 65 minutes

KeyError                                  Traceback (most recent call last)
<ipython-input-80-16937d860317> in <module>
      1 myElements = ['555fa11fe4b0e34068484fc5']
----> 2 findings= mycompany1.findComponentsUsage(myElements, verbose = True)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\aanalytics2\aanalytics2.py in findComponentsUsage(self, components, projectDetails, segments, calculatedMetrics, recursive, regexUsed, verbose, resetProjectDetails, rsidSuffix)
   1497             if verbose:
   1498                 print('retrieving projects details - long process')
-> 1499             self.projectDetails = self.getAllProjectDetails(verbose=verbose,rsidSuffix=rsidSuffix)
   1500             myProjectDetails = (self.projectsDetails[key].to_dict() for key in self.projectsDetails)
   1501         elif len(self.projectsDetails) > 0 and projectDetails is None and resetProjectDetails==False:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\aanalytics2\aanalytics2.py in getAllProjectDetails(self, projects, filterNameProject, filterNameOwner, useAttribute, cache, rsidSuffix, verbose)
   1353             print(f"estimated time required : {int(len(fullProjectIds)/60)} minutes")
   1354         projectIds = (project['id'] for project in fullProjectIds)
-> 1355         projectsDetails = {projectId:self.getProject(projectId,projectClass=True,rsidSuffix=rsidSuffix) for projectId in projectIds}
   1356         if filterNameProject is None and filterNameOwner is None:
   1357             self.projectsDetails = projectsDetails

~\AppData\Local\Continuum\anaconda3\lib\site-packages\aanalytics2\aanalytics2.py in <dictcomp>(.0)
   1353             print(f"estimated time required : {int(len(fullProjectIds)/60)} minutes")
   1354         projectIds = (project['id'] for project in fullProjectIds)
-> 1355         projectsDetails = {projectId:self.getProject(projectId,projectClass=True,rsidSuffix=rsidSuffix) for projectId in projectIds}
   1356         if filterNameProject is None and filterNameOwner is None:
   1357             self.projectsDetails = projectsDetails

~\AppData\Local\Continuum\anaconda3\lib\site-packages\aanalytics2\aanalytics2.py in getProject(self, projectId, projectClass, rsidSuffix, retry, cache, verbose)
   1306             if verbose:
   1307                 print('building an instance of Project class')
-> 1308             myProject = Project(res,rsidSuffix=rsidSuffix)
   1309             return myProject
   1310         if cache:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\aanalytics2\projects.py in __init__(self, projectDict, rsidSuffix)
     33             if definition.get('device', 'desktop') != 'cell':
     34                 self.reportType = "desktop"
---> 35                 infos = self._findPanelsInfos(definition['workspaces'][0])
     36                 self.nbPanels: int = infos["nb_Panels"]
     37                 self.nbSubPanels: int = 0

~\AppData\Local\Continuum\anaconda3\lib\site-packages\aanalytics2\projects.py in _findPanelsInfos(self, workspace)
     67             dict_data["panels"][panel['id']]['nb_subPanels'] = len(panel['subPanels'])
     68             dict_data["panels"][panel['id']]['subPanels_types'] = [subPanel['reportlet']['type'] for subPanel in
---> 69                                                                    panel['subPanels']]
     70         return dict_data
     71 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\aanalytics2\projects.py in <listcomp>(.0)
     66             dict_data["panels"][panel['id']]['name'] = panel.get('name', 'Default Name')
     67             dict_data["panels"][panel['id']]['nb_subPanels'] = len(panel['subPanels'])
---> 68             dict_data["panels"][panel['id']]['subPanels_types'] = [subPanel['reportlet']['type'] for subPanel in
     69                                                                    panel['subPanels']]
     70         return dict_data

KeyError: 'reportlet'

**Comment by nedwards-loop** [comment]
Getting a KeyError: 'reportlet'  -  any ideas on what I can do to fix? Thanks

**Comment by pitchmuc** [comment]
Hello 
Which version of aanalytics2 are you using ? 
it seems that there is one workspace without any reportlet inside...
Strange, I have used that on thousands of workspaces and never got that. 

I would try to download all projectsId via getProjects()
And then loop through all of these it via the method getProject(projectClass=True) to build a list with a try catch. 
That will help you identifying which project(s) failed. 

```python
list_details_projects = []
for myId in my_list_projectIds:
    try:
        list_details_projects.append(api2.getProject(myId, projectClass=True))
    except:
        print(f'project problem ID : {myId}')
```

You could then pass the list of projectIds in one of the parameters of findComponentsUsage. 

```python
myElements = ['555fa11fe4b0e34068484fc5'] 
findings= mycompany1.findComponentsUsage(myElements,projectDetails=list_details_projects, verbose = True)
```

**Comment by pitchmuc** [comment]
If you want me to fix that issue, you can send me the definition return by the normal 
`api2.getProject(myId, projectClass=False)`
Let me know I can give you my email address.

**Comment by nedwards-loop** [comment]
Hi - thanks for getting back to me. I am using this version (aanalytics2==0.2.8). It looks to be older project Ids that are causing the problem. Is there a way to retrieve IDs for workspaces created in the last year? Thanks

**Comment by nedwards-loop** [comment]
@pitchmuc  Hi, what is the correct format for passing the rsidSuffix ? I am running the below and not getting any results back... Thanks


```
z = ['prop10::rsid'] 
findings= mycompany1.findComponentsUsage(z,projectDetails=list_details_projects, rsidSuffix = True, verbose = True)
```

**Comment by pitchmuc** [comment]
You can filter the `created` field of the projects before then re-using it to retrieve the project details.

For rsidSuffix.
That seems to be the correct format for the rsidSuffix. Are you sure you are using the correct rsid or that you are using that prop10 somewhere in the projectDetails list you have sent ?

**Comment by nedwards-loop** [comment]
Hi, thanks for your help on this. Yes this can be closed. Cheers.
