### ISSUE TITLE
UnboundLocalError: local variable 'myProjectDetails' referenced before assignment

### ISSUE THREAD

**Issue by nedwards-loop** [pitchmuc/adobe-analytics-api-2.0#70]
`findings = mycompany1.findComponentsUsage(myElements,projectDetails=list_details_projects, verbose = True)`

I am passing through a list of workspace IDs in list_details_projects and get the following error:

`UnboundLocalError: local variable 'myProjectDetails' referenced before assignment`

It was working fine yesterday (22/08)...

Cheers
Nick

**Comment by nedwards-loop** [comment]
`\AppData\Local\Continuum\anaconda3\lib\site-packages\aanalytics2\aanalytics2.py in findComponentsUsage(self, components, projectDetails, segments, calculatedMetrics, recursive, regexUsed, verbose, resetProjectDetails, rsidSuffix)
   1512         else:
   1513             raise Exception("Project details were not able to be processed")
-> 1514         teeProjects:tuple = tee(myProjectDetails) ## duplicating the project generator for recursive pass (low memory - intensive computation)
   1515         returnObj = {element : {'segments':[],'calculatedMetrics':[],'projects':[]} for element in components}
   1516         recurseObj = defaultdict(list)

UnboundLocalError: local variable 'myProjectDetails' referenced before assignment
`

**Comment by pitchmuc** [comment]
Hello Nick
Thanks for raising the issue, I believe I need to be more descriptive in my docstring. 
The `projectDetails` argument takes a list... of Project detail instances. 

You would need to do a 3 steps process to make it run as you want to I believe. 
I assume you want to run the search on a selected amount of project. 

1. Retrieve all projects, with the `getProjects` method 
2. Get all project details with the method `getAllProjectDetails`, there you can pass the list or pandas dataframe with the sublist that you want.
3. pass the returned element to the `findComponentsUsage` on the `projectDetails` argument. 

I hope that helps.

**Comment by nedwards-loop** [comment]
Thanks for getting back to me. I was passing through a list of project id's like this:
`['56de8e0ebdf14b6045fdc5e9']`.

**Comment by pitchmuc** [comment]
I am closing the ticket as I improved the documentation on the last release.
