### ISSUE TITLE
getReport does not work with RequestCreator

### ISSUE THREAD

**Issue by caustinbrooks** [pitchmuc/adobe-analytics-api-2.0#76]
When running getReport with a populated RequestCreator object, the getReport function raises `TypeError: argument of type 'RequestCreator' is not iterable`

```python
#print(type(test_report))
#<class 'aanalytics2.requestCreator.RequestCreator'>
myreport = mycompany.getReport(test_report)
```

It errors at line 2432:

https://github.com/pitchmuc/adobe-analytics-api-2.0/blob/658899c842fd4a68db2ef6caf939949296ef846d/aanalytics2/aanalytics2.py#L2425-L2440

One solution would be the following:

```python
 elif type(json_request) == str and '.json' in json_request: 
     try: 
         with open(Path(json_request), 'r') as file: 
             file_string = file.read() 
         request = json.loads(file_string) 
     except: 
         raise TypeError("expected a parsable string") 
```

Another would be to move the RequestCreator instance check above the erroring line.

```python
 elif isinstance(json_request,RequestCreator): 
     request = json_request.to_dict() 

 elif '.json' in json_request: 
     try: 
         with open(Path(json_request), 'r') as file: 
             file_string = file.read() 
         request = json.loads(file_string) 
     except: 
         raise TypeError("expected a parsable string") 
```

**Comment by pitchmuc** [comment]
Hello @caustinbrooks and thanks for looking to way to make it work. 
The easiest way for it to make it work is to use the `to_dict()` method on your RequestCreator instance. 
Such as: 
```python
myreport = mycompany.getReport(test_report.to_dict())
``` 

That being said, it will be supported in the next release that I am planning to do in the next week. 
Many more things will come, especially the `getReport2` method.

I am starting to document them now: 
https://github.com/pitchmuc/adobe-analytics-api-2.0/blob/master/docs/releases.md

**Comment by pitchmuc** [comment]
Hello @caustinbrooks
Normally the release of yesterday was providing support for the RequestCreator. 
Can you try if this issue is fixed when you upgrade your installation ?
