### ISSUE TITLE
createConfigFile() Improved argument parsing

### ISSUE THREAD

**Issue by doug-cresswell** [pitchmuc/adobe-analytics-api-2.0#79]
## creatConfigFile destination argument

I've just been playing around with the library and found a couple of "gotchas" when creating config files using 'createConfigFile()'. These should be quite simple to mitigate, by adding some parsing and error raise logic to the function. If I can find some time this week I'll happily create a branch and PR. 

### Example 1
Invalid file extensions are not recognised or updated in `destination=` arg:
```
>>> import aanalytics2 as api2
>>> CONFIG_FILE = "config.ini"
>>> api2.createConfigFile(destination=CONFIG_FILE)
```
_... this creates a config file named `config.ini.json`_

### Example 2
createConfigFile does not support `PosixPath` type, error is not user-friendly:
```
>>> from pathlib import Path
>>> import aanalytics2 as api2
>>> CONFIG_PATH = Path("config.json")
>>> api2.createConfigFile(destination=CONFIG_PATH)
  File "/opt/miniconda3/envs/adobe_api/lib/python3.10/site-packages/aanalytics2/configs.py", line 41, in createConfigFile
    if '.json' not in destination:
TypeError: argument of type 'PosixPath' is not iterable
```

### Proposed Solutions

- [ ] explicit `str()` type conversion
- [ ] or.. if `isinstance(destination, PosixPath)`
- [x] use `pathlib.Path()` to split file path and replace extension

**Comment by pitchmuc** [comment]
Thanks for these ideas. 
I have a new version coming at some point, I'll try to get a solution for both challenges.

For the 1st point: 
What would you expect as outcome for the ".init" name ? 
adding a json extension should make the file workable. Is that a problem somehow ? 

for the 2nd point: 
I like the idea to use the pathlib.Path capability as I believe I already use this module.
I would need to adjust the check of the extension type with that but definitely doable.

**Comment by doug-cresswell** [comment]
> Thanks for these ideas. I have a new version coming at some point, I'll try to get a solution for both challenges.

I'm happy to put in some dev time, I'm looking to do some more open source contribution work.


> For the 1st point: What would you expect as outcome for the ".init" name ? adding a json extension should make the file workable. Is that a problem somehow ?

I was thinking use pathlib to parse out the file extension. Then if there is no file extension, append `.json` to the path, and if there is an extension that's not supported, replace it with `.json` and give a `logging.warn(msg)`.

> for the 2nd point: I like the idea to use the pathlib.Path capability as I believe I already use this module. I would need to adjust the check of the extension type with that but definitely doable.

Yes. I would think only 10-20 lines of code required

**Comment by pitchmuc** [comment]
Closing it as it is being developed parallely.
