### ISSUE TITLE
Limit

### ISSUE THREAD

**Issue by leighlewis25** [pitchmuc/adobe-analytics-api-2.0#85]
Hi,

Why is there a limit of 999 rows? Even when I try to change the limit in settings in the json file or try to change the page, I always get the first 999 rows. Please assist.

**Comment by pitchmuc** [comment]
Hello
Thanks for using the module. Are you using `getReport` or `getReport2` method ? I would recommend to use the `getReport2` method.
In any case, the JSON request is overriden by the method and you can use the `limit` parameter to define how many results you want... per request. The `n_results` parameter is the total amount of result you want to have. 
You can refer to this method documentation to see the possible parameters that can be used: 

* [getReport](https://github.com/pitchmuc/adobe-analytics-api-2.0/blob/master/docs/main.md#get-report)
* [getReport2](https://github.com/pitchmuc/adobe-analytics-api-2.0/blob/master/docs/main.md#getreport2)


out of curiosity, how do you load your request configurartion ? Do you use the RequestCreator or directly the dictionary from the JSON ? 

let me know if I can be of any help.

**Comment by pitchmuc** [comment]
No response for a month, I think the answer lies in the documentation anyway. I am closing this bug.
