### ISSUE TITLE
Bug: DataFrame obtained from getReport method not matching table seen in Adobe Analytics portal.

### ISSUE THREAD

**Issue by cyaris** [pitchmuc/adobe-analytics-api-2.0#87]
I go to the Adobe Analytics portal and get my `JSON` request here (_see photo below_).

<img width="312" alt="Screen Shot 2023-02-02 at 12 04 36 PM" src="https://user-images.githubusercontent.com/35279417/216406784-a8a255da-2cb9-4f70-9a41-6c563978a8a4.png">

Then, I pass the `JSON` request through the `getReport` method and compare the results with those seen in the Adobe Analytics portal.

**Bug:** The values in the `dataframe` returned by the `getReport` method differ greatly from those shown in the table in the Adobe Analytics portal. Everything is correct EXCEPT the numbers seen in the `dataframe`. The size of the`dataframe`, as well as the `dimension`, `filters`, `metrics` and `rsid` are all correct.

**Note:** No errors are thrown by `aanalytics2`. I've tried multiple files and have checked that the filter selections used in the portal match those seen in the `JSON` request.

**Comment by pitchmuc** [comment]
Hello @cyaris 
Sorry it took some time to answer. 
You need to use the `Free Form` table JSON and not the one from Sparkline.

**Comment by cyaris** [comment]
@pitchmuc that worked. Thanks so much for your help!

**Comment by pitchmuc** [comment]
Very welcome
