### ISSUE TITLE
Updating segment error

### ISSUE THREAD

**Issue by ahaddadl** [pitchmuc/adobe-analytics-api-2.0#88]
I have created a Service Account (JWT), within the project “API Access”, in Adobe. No problem when reading segment información, or creating a new segment. But when i try to update a segment i am getting this  error:  

updateSegment = ags.updateSegment('s2571_63e7c27a72073f71d4b9865d',segment_2)
updateSegment

{'errorCode': 'insufficient_access',
 'errorDescription': 'No editing access to this item granted. Userid=200423211 does not match ownerid=200283947',
 'errorId': '244625f1-8169-4ebd-8b3d-41fe2878fd8a'}

**Comment by pitchmuc** [comment]
Hello @ahaddadl 
You can not edit the segment of other users apparently (no permision). You can duplicate the definition if you want and then update that one.
