### ISSUE TITLE
getReport2 should not rewrite the request

### ISSUE THREAD

**Issue by loldenburg** [pitchmuc/adobe-analytics-api-2.0#96]
If I query a report with getReport2, the request dictionary gets rewritten. Eg, if I send through a global Segment Filter with a name, but no segmentId (which is perfectly valid as long as there is a definition), getReport2 adds an artificial segmentId "Dynamic hits None without" and even changes the name of the segment to "hits None"!

See this example video:
https://www.loom.com/share/2ddf82322bd8417190bb5c2c1d871111

The biggest problem with this for me is that I always need to store a deepcopy of the request dictionary somewhere and I cannot use the request dictionary for an ensuing request. I cannot even re-issue the same request again (e.g. if it failed due to some network issue), because the segmentId "hits None" will not retrieve any data from Adobe.

**Comment by loldenburg** [comment]
@pitchmuc sorry forgot to mention you. ;)

**Comment by pitchmuc** [comment]
Hey @loldenburg, yes I know, I think one of the latest bug was also providing me this type of feedback in the background. (see https://github.com/pitchmuc/adobe-analytics-api-2.0/issues/95) 
I was not respecting the parameter passed in the JSON and overwrite them by the default value pass as parameter. 
So you would be able to run the same request but you need to tweak the parameter, which obviously the basic AA user do not even know they existed in the first place. :D 

I will look into that specific example you gave me. 

Make sure you have the latest version of the aanalytics2 library as well, as I solve some of these problems already. 

I am in the middle to update the authentication method to support the new Oauth V2 token and I hope to be able to do a global release to fix that and support the new Oauth V2 token at the same time. 
Hopefully you can wait ~10 days for that (hopefully faster but let's see)

**Comment by loldenburg** [comment]
Thanks, I do have the newest library (aanalytics2 0.3.3.post3) I think. No hurry with the fix. I have a workaround now in that one script where this request rewriting causes most of the trouble. My wrapper around your wrapper saves a deepcopy of the request before it passes it to getReport2, and if getReport2 fails, it retries with another deepcopy of the deepcopy :D But of course that is suboptimal. 

Updating to support oAUTH V2 is amazing!
MERCI BEAUCOUP!

**Comment by pitchmuc** [comment]
Please bear with me as it takes a bit more time. 
Summit and the AEP user rights modification created delay with verification of Oauth Server to Server compatibility.

**Comment by pitchmuc** [comment]
Another small question: 
I do not do a deepcopy yet of the request but I propose it via the Workspace instance. 
You can retrieve it via this type of call : 
```python
myData = aa2.getReport2(myrequest)
myData.dataRequest ## your request. 
```
Have you tried that ? 

Sorry it is unclear on the video where you grab the _req variable. 
I will make sure that the 
`myData.dataRequest` attribute is a deepcopy of the request you have passed, before I finalize it.
So you can get your original request back.

**Comment by pitchmuc** [comment]
btw: I modify it when I am building the report afterwards via the Workspace class. 
In order to ensure that I can give a name to the segment for the dataframe, I am building a segment name based on the context I can find on the segment. 
In your case, it is a Hit segment with None search. 

I am trying my best (probably too hard) to make it easily readable by users.

**Comment by loldenburg** [comment]
> Small question @loldenburg, The request is being rewritten (gonna be fixed - deepcopy is a good idea), but it works, correct ? I do not have to fix that ?

The request works, just if it fails and you then want to try it again, it does not work because it has been re-written.

Q2: "Have you tried this?"
No. I still think the original request JSON should not be modified by the wrapper, even if you offer this option.

"Sorry it is unclear on the video where you grab the _req variable.
It seems you are trying to access a global variable, which will obviously get used.
I am not using Rust yet :D so I do not borrow things, I own them once they are passed. (For better of worse :D )
I would not have think that someone wants to have that original memory cache variable to stay unchanged.
It is interesting."

I am simply doing sth like:
```
req = {...} # the JSON request
req_copy = copy.deepcopy(req)
print(req == req_copy) # True
report = aa2.getReport2(req)
req == req_copy # now it is False, and that is highly unexpected, the wrapper should not change the request input, it should just return the response
```
As the code shows, `req` is no longer the original JSON request, but what the AA wrapper has rewritten it to. That is imho not how it should work, the original request JSON should remain unchanged so I can use it for the next request (and eg change it a bit for a similar report, e.g. try the same request, but with another segment on top).

Q3
"Question n°3
Do you want to have a deep copy of your original request in that attribute ? Or the one you have use with the possible parameter modification you could use via getReport2.
I am thinking the latter, so you have a copy of the real request that is sent to Adobe Analytics.

I hope these questions make sense"
=> Not sure if I understand. I just don't want the wrapper to modify the request I hand to the wrapper in any form in my scope, so creating a deepcopy of it and then doing your work on your end will do it. Just like when I hand a parameter to a function, I expect the function to work with the parameter, but not change its value in the outer scope.

**Comment by loldenburg** [comment]
In other words, if your wrapper is a worker with a shovel whom I can give directions (request) to dig out a treasure chest (report data), I don't expect you to have my directions changed after I receive the treasure chest. Maybe in the sense of "we normalized your directions, see the alternative here", but not simply discard and overwrite the original directions.

**Comment by pitchmuc** [comment]
I have updated the behavior of the getReport2 and Workspace elements. 
it should now work as you would expect, you can always retrieve the element on your attribute. 
You can test now based on this git push : [172d9ce](https://github.com/pitchmuc/adobe-analytics-api-2.0/commit/172d9ce8f5074664bf4916a1769d1edb58757253)

Or wait for when I publish it, I have other change to take care of.

**Comment by loldenburg** [comment]
Thanks a ton, very much appreciated.
I am really full this week so might not have time to test.

**Comment by loldenburg** [comment]
Sorry, finally found time to verify this now. It looks good now, thanks a lot! The request is no longer rewritten.
